services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - SESSION_SECRET=sessionsecret
    command: node index.js